### ISSUE TITLE
Anzeige von Räumen teilweise leer

### ISSUE THREAD

**Issue by Folcr** [hobbyquaker/yahui#7]
ccu.io: 0.9.97
yahui: 1.2.3
Sieht soweit alles ganz gut aus. Allerdings werden in den Räumen zwei von sieben Räumen leer (keine Objekte nur die Menüs) angezeigt. \datastore\yahui-extensions.js verfügbar sonst nichts.
Bin zunächst wieder auf 0.9.74 und 1.2.0 zurückgefallen. Da funktioniert alles.
GRuss Folcr.

**Comment by hobbyquaker** [comment]
Hallo Folcr!
Würde mir das gerne anschauen, kannst Du mir die regaObjects sowie die Namen der Räume bei denen das auftritt zukommen lassen?
Grüße
HQ

**Comment by Folcr** [comment]
Hi Sebastian,
klar mache ich nach der Arbeit.
Gruss Volker.

Am 19. November 2013 20:22 schrieb hobbyquaker notifications@github.com:

> Hallo Folcr!
> Würde mir das gerne anschauen, kannst Du mir die regaObjects sowie die
> Namen der Räume bei denen das auftritt zukommen lassen?
> Grüße
> HQ
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/hobbyquaker/yahui/issues/7#issuecomment-28823495
> .

## 

MfG Volker Braun,

http://volki.gmxhome.de/
Google+ http://volki.gmxhome.de/+
Neufferstrasse 55, D-70469 Stuttgart (Feuerbach)
Tel: +49(711)82069-16 | Fax: +49(711)820868-91

**Comment by Folcr** [comment]
Hallo Sebastian,
ich bin mittlerweile aufCCU.IO Version 0.9.83 und yahui 1.2.3. Immernoch das selbe nur 2 von den Räumen mit Namen "Obergeschoss" und "Keller" sind leer, was nicht korrekt ist.
Die regaObject lasse ich dir anders zukommen ist zu lage für hier.

**Comment by ghost** [comment]
Hallo Volker,

welchen Browser benutzt Du? Magst Du dort mal die Entwicklerkonsole aktivieren und nach JavaScript-Fehlern schauen (geht bei Firefox/Chrome/IE10 über die Taste F12) und dann auf dem Reiter Konsole nachsehen ob etwas beim Anzeigen der Räume ausgegeben wird.

Viele Grüße!

André

Von: Volker B. [mailto:notifications@github.com] 
Gesendet: Donnerstag, 21. November 2013 20:01
An: hobbyquaker/yahui
Betreff: Re: [yahui] Anzeige von Räumen teilweise leer (#7)

Hallo Sebastian, 
ich bin mittlerweile auf CCU.IO Version 0.9.83 und yahui 1.2.3. Immernoch 
das selbe nur 2 von den Räumen mit Namen "Obergeschoss" und "Keller" sind 
leer, was nicht korrekt ist. 

Am 20. November 2013 11:45 schrieb Volker Braun < 
volker.m.braun@googlemail.com>: 

> Hi Sebastian, 
> klar mache ich nach der Arbeit. 
> Gruss Volker. 
> 
> Am 19. November 2013 20:22 schrieb hobbyquaker notifications@github.com: 
> 
> Hallo Folcr! 
> 
> > Würde mir das gerne anschauen, kannst Du mir die regaObjects sowie die 
> > Namen der Räume bei denen das auftritt zukommen lassen? 
> > Grüße 
> > HQ 
> > 
> > — 
> > Reply to this email directly or view it on GitHubhttps://github.com/hobbyquaker/yahui/issues/7#issuecomment-28823495 
> > . 
> 
> ## 
> 
> MfG Volker Braun, 
> 
> http://volki.gmxhome.de/ 
> Google+ http://volki.gmxhome.de/+ 
> Neufferstrasse 55, D-70469 Stuttgart (Feuerbach) 
> Tel: +49(711)82069-16 | Fax: +49(711)820868-91 

## 

MfG Volker Braun, 

http://volki.gmxhome.de/ 
Google+ http://volki.gmxhome.de/+ 
Neufferstrasse 55, D-70469 Stuttgart (Feuerbach) 
Tel: +49(711)82069-16 | Fax: +49(711)820868-91

**Comment by hobbyquaker** [comment]
sollte mit 1.2.5 ausgemerzt sein, war ein Bug wenn ein Geräte vom HssType PING ein ALIVE Datenpunkt (alte CUxD Versionen) mitgebracht hat.
