### ISSUE TITLE
[FEATURE] Add to Homescreen auf Android

### ISSUE THREAD

**Issue by pasarn** [hobbyquaker/yahui#9]
Hi,

es währe toll, wenn yahui die "Add to Homescreen" Funktion in Android unterstützen würde.
Damit lassen sich Webseiten wie Apps darstellen.

Weitere Infos gibt es hier: https://developers.google.com/chrome/mobile/docs/installtohomescreen

Gruß
Pascal

**Comment by hobbyquaker** [comment]
kommt auf die Todo!
Grüße
